### ISSUE TITLE
Use github actions to have benchmarks directly in log

### ISSUE THREAD

**Issue by Dudeplayz** [wokwi/avr8js-research#1]
Hey. I would suggest to configure some basic npm github action to run the implemented benchmark tests to have them available without the need to clone the project.

**Comment by urish** [comment]
Sounds like a good idea! Do you need any help with that?

**Comment by Dudeplayz** [comment]
Hey, I will try it by myself. I have already found the related information I need. It was just to late yesterday :D.
If there are any problems I let you know :)!

**Comment by Dudeplayz** [comment]
The benchmark results are now visible in the CI job.
